### ISSUE TITLE
digital ocean spaces support

### ISSUE THREAD

**Issue by pjebs** [archiecobbs/s3backer#100]
Digital Ocean spaces claims to be S3 compatible in terms of their API and how it can be interfaced by external clients. Should s3backer work in theory?

**Comment by archiecobbs** [comment]
I guess so... "in theory"...

**Comment by buddye** [comment]
I beta tested it on on NYC3 but didn't get great performance from Seattle. But,  trying SFO2 tonight will let you know.  I used blockSize=1m before, but since I only have very large files trying blockSize=8m

My config:

sudo s3backer --baseURL=https://sfo2.digitaloceanspaces.com/ --vhost --ssl --blockCacheFile=/NetVolumes/your_cache_file.cache --blockCacheSize=10000 --prefix=s3b --filename=your_dmg_file.dmg --blockSize=8m --size=1t --accessFile=/NetVolumes/.your_access_file your-spaces-name-in-sfo2 /NetVolumes/your_mount_file.mnt

**Comment by archiecobbs** [comment]
Resolving issue. Feel free to re-open if there is a concern.
