### ISSUE TITLE
How to support concurrent writing

### ISSUE THREAD

**Issue by Roay** [archiecobbs/s3backer#101]
@archiecobbs 
Now the fuse3.0 version has supported concurrent write operations, that is, multiple threads get writing requests from /dev/fuse simultaneously.
**Can s3backer support concurrent writing?**

**Comment by archiecobbs** [comment]
In principle, yes.

Note you'd get the same effect by using a local on-disk cache, albeit at the cost of taking up some local disk space.

It should be straightforward to add the {{FUSE_WRITEBACK_CACHE}} flag and try it... though I haven't tried this.

**Comment by uroni** [comment]
You'll get best performance if you use a loop device with direct io (losetup --direct-io=on) and with my patch https://github.com/torvalds/linux/commit/23c94e1cdcbf5953cd380555d0781caa42311870 which will finally be in Linux 5.1. That way it'll have /sys/block/loopX/queue/nr_requests parallel read/writes at a time and won't cache the block device twice.

**Comment by crossmeta** [comment]
Checking whether this issue   @crossmeta/cxfuse/#5 can be related. Because of Linux FUSE limitation s3backer was not subjected to concurrent writes!? Also there is a large write request of 1MB from format command.

From the debug messages my analysis is that s3backer received overlapped write request for some block that was already sent out on active CURL request. It decides to cancel that as new writes have come to the same block?  All okay but somehow application gets IO error for the canceled CURL request.  @archiecobbs  can you provide some hints. Otherwise write operations are fine as long as it doesn't hit this canceled write.

**Comment by archiecobbs** [comment]
@crossmeta, in s3backer, just because the write of a block is canceled, that should not cause an error to be returned all the way back up the stack to the original caller. Instead, the thread that was waiting on the canceled write will retry.

The only place in the code where cancellation is allowed is in `block_cache.c`.

You can see here that it retries on any error (including `ECONNABORTED`, which is the hallmark of cancellation):
```c

/* Attempt to write the block */
pthread_mutex_unlock(&priv->mutex);
r = (*priv->inner->write_block)(priv->inner, entry->block_num, buf, md5, block_cache_check_cancel, priv);
pthread_mutex_lock(&priv->mutex);
S3BCACHE_CHECK_INVARIANTS(priv);

/* Sanity checks */
assert(ENTRY_GET_STATE(entry) == WRITING || ENTRY_GET_STATE(entry) == WRITING2);

/* If write attempt failed (or we canceled it), go back to the DIRTY state and try again later */
if (r != 0) {
    entry->dirty = 1;
    TAILQ_INSERT_HEAD(&priv->dirties, entry, link);
    continue;
}

```

**Comment by archiecobbs** [comment]
Closing issue, as no s3backer-specific bug identified yet. Feel free to re-open if needed.
