### ISSUE TITLE
s3backer appears to be waiting to write dirty blocks, even with blockCacheMaxDirty=0

### ISSUE THREAD

**Issue by JustinLovinger** [archiecobbs/s3backer#121]
I'm observing behavior with s3backer that seems to indicate waiting to write dirty blocks. During a large transfer into s3backer, the first 3GB are quickly transferred, before write speed drops to the rate of my network upload speed. Max dirty blocks is set to unlimited (0), md5 cache is set to unlimited (the number of blocks in s3backer), and the cache is far from full. I see no reason for writes to delay like this.

**Comment by archiecobbs** [comment]
How are you starting s3backer (i.e., what flags)? Also what version?

**Comment by JustinLovinger** [comment]
I am running s3backer 1.5.4 and the command looks like

```
s3backer \
  -f \
  --accessFile=ACCESSFILE \
  --blockSize=128k --size=1t \
  --encrypt --passwordFile=PASSWORDFILE \
  --compress=9 \
  --blockCacheFile=BLOCKCACHEFILE --blockCacheSize=1638400 --blockCacheRecoverDirtyBlocks \
  --md5CacheSize=8388608 \
  --ssl \
  BUCKET --region=REGION \
  MOUNTPOINT
```

**Comment by archiecobbs** [comment]
Thanks. One thing to try is adding the `--listBlocks` flag.

If your upper filesystem block size is smaller than 128k, then without this flag `s3backer` has to read a block (even an empty one) before it can perform a partial write to that block. Not sure if this is really the problem, just thought I'd point it out while I'm thinking of it.

Otherwise I don't see any problem with how you're invoking it.

Try runing `watch cat /mnt/stats` and watching the statistics... what appears to be happening?

**Comment by JustinLovinger** [comment]
I don't see anything strange in the stats file. Dirty ratio is zero, block cache is slowly filing, and http write requests are sending. md5 cache is small. There are no errors.

I'm not sure what `block_cache_write_misses` means. How do you miss a cache write? Regardless `block_cache_write_hit_ratio` is 0.9708.

`md5_cache_write_delays` is 695.276 sec but that's not changing over time.

Even if s3backer has to read blocks before writing to them, that shouldn't block it from writing to the cache, right?

**Comment by archiecobbs** [comment]
`block_cache_write_misses` is a write to the cache of a block that is not already in the cache. The opposite is `block_cache_write_hits`.

The high `write_hit_ratio` might be odd. That means most writes are going to blocks already in the cache. E.g., could just be that you're using a journaling filesystem (nothing wrong with that).

If the dirty ratio is close to zero (i.e., very few dirty blocks), then the problem is not that `s3backer` is being slow writing dirty blocks, it means that there are not very many dirty blocks for it to write, i.e., maybe something is slowing down the writing of data before it reaches `s3backer`.

Not really sure what's going on... you could try some experiments with `dd` on the raw `s3backer` file...

**Comment by JustinLovinger** [comment]
I am testing `--listBlocks` now. Performance appears better so far. It is difficult to tell because the write speed is oscillating between very fast and very slow. However, the dirty cache ratio is greater than zero. Performance is still slower than I expected, but, if it the filesystem is waiting for network reads before it can write, then that would explain the periods of slow write performance. Monitoring the stats file shows that it is downloading a few non-zero blocks per second.

**Comment by archiecobbs** [comment]
> I expected the cache to be fully loaded because the cache size is greater than the filesystem size

What precisely do you mean by "filesystem size"?

What is your upper filesystem? It's possible that it intentionally does not reuse disk blocks, as part of the way it works (i.e., for performance reasons).

> Edit 2: http_normal_blocks_read is increasing even though block_cache_read_hits and block_cache_read_misses is not changing. Is it not using the cache for some reason?

The block cache stats don't count blocks that are read due to (a) read-ahead, or (b) partial writes. 

To eliminate one variable you could disable read-ahead (see `--readAhead` and `--readAheadTrigger`).

**Comment by JustinLovinger** [comment]
> What precisely do you mean by "filesystem size"?

By filesystem size, I meant the disk usage of the filesystem.

> What is your upper filesystem? It's possible that it intentionally does not reuse disk blocks, as part of the way it works (i.e., for performance reasons).

Now that you mention it, the upper filesystem is ZFS, a copy-on-write filesystem, which could account for the cache behavior.

It sounds like the primary source of slowdown is partial writes requiring network reads, and the only way I see to mitigate that further is to decrease the s3backer block size to reduce partial writes, but that has it's own tradeoffs.

It doesn't seem like a bug in s3backer itself, just an interaction between s3backer and the filesystem that I didn't foresee, so I think we can close this.

**Comment by archiecobbs** [comment]
OK thanks. Interesting case really.

If you can stand to start over completely, you could try this test.

First, erase the entire thing (`s3backer --erase`) to remove all blocks.

The read-before-write is only needed when `s3backer` doesn't already know the block is zero. So immediately after a complete erasure, as long as you startup with `--listBlocks`, then it should not be necessary to read-before-write any block until after the cache has filled completely.

It would be nice to verify this logic...
