### ISSUE TITLE
System hangs on fast concurrent creation of files

### ISSUE THREAD

**Issue by brianredbeard** [archiecobbs/s3backer#133]
I've been running into an issue where s3backer causes the load to spike up to the point where the system crashes when quickly creating files.  I've found I can reproduce this with kernel sources: https://cdn.kernel.org/pub/linux/kernel/v3.0/linux-3.0.tar.gz

When unpacked onto a local disk everything is speedy:
```
$ time tar zxf /tmp/linux-3.0.tar.gz 

real	0m4.956s
user	0m3.501s
sys	0m2.397s
```

When unpacked into _into_ an s3backer file system, the load begins to climb as threads are held in `iowait`.  There is no state where the host recovers, except if a connection is held open and the untar is cancelled via ctrl+c.

This "feels" related to #132.  I broke out the `valgrind` tool set to attempt to troubleshoot, out it began warning on so many hanging file descriptors that I'm reigning this issue back in scope (though I would consider taking a look at the output of `valgrind`).

In my experience, generally the maximum number of threads you'll be able to hit (without contention) for I/O bound workloads is going to be either your number of cores or 2x your number of cores, in the event that you've left hyperthreading on (and thus leaving open a number of attack vectors when it comes to speculative execution attacks).  

The easiest way to check out your raw number of cores is to introspect `/proc/cpuinfo`, e.g.:

```bash
[~]$ grep processor /proc/cpuinfo 
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
processor	: 5
processor	: 6
processor	: 7
```

A secondary consideration would also be to just default to either `<NUM_CORES>` or some multiple of `<NUM_CORES>`.  This is the behavior of many applications, for example [NGINX](https://docs.nginx.com/nginx/admin-guide/basic-functionality/runtime-control/) (NGINX defaults to setting `worker_processes` to the number of available cores, unless a user chooses to set this to some other value).

**Comment by archiecobbs** [comment]
As in #132, we don't control the number of read/write threads coming from the kernel; instead, FUSE does. All we can do is stop them from consuming CPU, which is exactly what we're doing with our slow network I/O :)

So maybe this is an issue for the FUSE developers to look at.

Regarding maximum number of threads, I don't understand what you're talking about. It's true that it is not very useful to have more threads than cores _when you are CPU bound_, however this is certainly not the case when you are I/O bound. Otherwise every web server in the world is misconfigured. The only resource a thread blocked waiting on I/O consumes is memory.

**Comment by alokdhir** [comment]
fwiw, i was able to fetch and untar that kernel 3 tarball without issue.. blocksize = 64k, cachesize is also 64k

**Comment by archiecobbs** [comment]
Good to hear... there may have been a bug in there somewhere that got fixed in the recent changes.

Closing issue for now, feel free to reopen if you see further problems.
