### ISSUE TITLE
write aborted: PUT

### ISSUE THREAD

**Issue by acsfer** [archiecobbs/s3backer#164]
I'm using Storj as a S3 compatible service.
I was having some 500/502/503 and retried requests so i've reached their support:

> It's better to do not use small files, the service is optimised to work with 64 mb segments.
> I would like to suggest to run s3backer with `--blockSize=67108864` option.

I've then created a new bucket with that blocksize, but i just can't upload anything to it trough my filesystem.
After i've enabled `--debug` and `--debug-http`, it only outputs this **in a loop**:

```
DEBUG: PUT https://gateway.eu1.storjshare.io/w3uxou1shkbtsi3m/c448b72c-00000000
* Too old connection (144 seconds), disconnect it
* Connection 0 seems to be dead!
* Closing connection 0
*   Trying 2a10:c640:0:1::3:443...
* TCP_NODELAY set
* Connected to gateway.eu1.storjshare.io (2a10:c640:0:1::3) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=gateway.storjshare.io
*  start date: Jan  8 15:12:50 2022 GMT
*  expire date: Apr  8 15:12:49 2022 GMT
*  subjectAltName: host "gateway.eu1.storjshare.io" matched cert's "gateway.eu1.storjshare.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f35040058e0)
> PUT /w3uxou1shkbtsi3m/c448b72c-00000000 HTTP/2
Host: gateway.eu1.storjshare.io
user-agent: s3backer/1.6.3/1.6.3
accept: */*
content-encoding: deflate, encrypt-AES-128-CBC
date: Sat, 29 Jan 2022 22:25:25 GMT
content-type: application/x-s3backer-block
content-md5: DTDMWg4IOOJYbSapWyYdyA==
x-amz-acl: private
x-amz-meta-s3backer-blocksize: 67108864
x-amz-meta-s3backer-filesize: 1099511627776000
x-amz-meta-s3backer-hmac: "9efb1265f192a87cd8c8112d109ade4f2e714742"
authorization: AWS jw5ayvrhpz7vmxzcocqxyjn4ileq:87ciECp7CVhDGHS5X0qTUbMtBtE=
content-length: 8087856

* old SSL session ID is stale, removing
* operation aborted by callback
* stopped the pause stream!
* Connection #1 to host gateway.eu1.storjshare.io left intact
DEBUG: write aborted: PUT https://gateway.eu1.storjshare.io/w3uxou1shkbtsi3m/c448b72c-00000000
```

Whole configuration file is:

```
# s3backer config

# Geometry
--size=1000t
--blockSize=67108864

# Credentials
--baseURL=https://gateway.eu1.storjshare.io/
--accessFile=/etc/s3b/storj-creds
--authVersion=aws2

# List blocks on startup
--listBlocks
--listBlocksThreads=128

# Encryption
--ssl
--encrypt
--passwordFile=/etc/s3b/passwd

# Block cache
--blockCacheSize=120000
--blockCacheFile=/var/cache/s3bCacheFile
--blockCacheMaxDirty=200
--blockCacheThreads=60
--blockCacheNumProtected=3000
--blockCacheRecoverDirtyBlocks
--blockHashPrefix

# MD5
--md5CacheSize=12000
--md5CacheTime=120000

# Misc
--timeout=300
--debug
--debug-http
--readAhead=16
--readAheadTrigger=4
```

It works (beside the retried errors) if i use a much lower `--blockSize`, like 256k
My filesystem is `btrfs`.

The only issue i've found with a similar error message is https://github.com/archiecobbs/s3backer/issues/135

Should a Storj bucket be necessary to help sort this out, one can be obtained (150 GB) **for free** at https://www.storj.io/

**Comment by archiecobbs** [comment]
One 64mb s3backer block would hold 16,384 4k filesystem blocks (or 4096 16k filesystem blocks).

Because of this dramatic mismatch you want to make sure that you're not stepping on yourself. The `write aborted` message is normal and reflects that event - it means "I was in the middle of sending a block to S3, and but a new write inside that block occurred while I was still transmitting the old version, so I'm going to abort sending the first version (why continue??) and start over with sending the new version".

Actually "why continue??" is a good question - s3backer could be smarter, and know to continue anyway in situations where it keeps getting interrupted. Right now it always aborts.

This is going to happen a lot with (a) large s3backer block sizes which take longer to transmit, and (b) big mismatch between upper filesystem and s3backer block sizes which means multiple (partial) writes will occur into each s3backer block.

You can absorb much of this with the cache, but you need to configure it to give it more of a chance. One problem here is s3backer's default `--blockCacheWriteDelay` is only 250ms. Try bumping that up a good bit.

You might also increase `--blockCacheMaxDirty` so blocks can sit in the cache longer, where they may absorb more updates.

> It's better to do not use small files, the service is optimised to work with 64 mb segments. I would like to suggest to run s3backer with --blockSize=67108864 option.

Hmm. Maybe you should tell them that optimizing their service is their problem, not yours.

**Comment by acsfer** [comment]
> Hmm. Maybe you should tell them that optimizing their service is their problem, not yours.

Let's agree on this because after several tests and tuning, I can't get it working properly 👍
