### ISSUE TITLE
Deeper understanding of the block cache

### ISSUE THREAD

**Issue by HaleTom** [archiecobbs/s3backer#173]
* I think @alaric728 raised an interesting question in #172: Are there any situations in which there is value to having more workers than there are blocks in the cache?

Just checking my understanding, on these, I hope the answers are Yes x2:

* Do I understand correctly that we could partition the cache into write cache and read cache by setting `--md5CacheSize`:  Only a maximum of `md5CacheSize` blocks can be in the queue for writing. The actual number in the write cache will be less than that maximum because previously written blocks will still be cached in the md5 cache for for `--md5CacheTime`.

* If using `--blockCacheSync --blockCacheWriteDelay=0` the benefit of using a cache that multiple blocks may simultaneously be writing before the write request for each completes?

**Comment by archiecobbs** [comment]
> Are there any situations in which there is value to having more workers than there are blocks in the cache?

The worker threads write blocks, and a block can be written by at most one worker at a time, so therefore no.

>  Only a maximum of `md5CacheSize` blocks can be in the queue for writing

Depends on what you mean by "in the queue for writing". The block cache and the MD5 cache are entirely separate layers; the latter sits below the former in the stack.

The MD5 cache size imposes a limit on how many writes can happen in a `md5CacheTime` time window, because it has to keep track of them for that long and there are only `mdCacheSize` slots available. The MD5 cache does not cache data; it only caches write timestamps and MD5 checksums.

The block cache can have up to `MIN(blockCacheSize, blockCacheMaxDirty)` blocks "in the queue for writing", i.e., in the cache and in a "dirty" state.

> If using `--blockCacheSync --blockCacheWriteDelay=0` the benefit of using a cache [is] that multiple blocks may simultaneously be writing before the write request for each completes?

I think the meaning of `--blockCacheSync --blockCacheWriteDelay=0` is better described as: "Perform all writes immediately and synchronously; do not return a 'success' result to the kernel until the actual HTTP request completes".

**Comment by archiecobbs** [comment]
Closing issue. Feel free to re-open if there are new issues or questions.
