### ISSUE TITLE
Zero blocks should not take up space in block or md5 caches

### ISSUE THREAD

**Issue by reidrankin** [archiecobbs/s3backer#61]
Doing some investigation as to why mkfs for ext4 is extremely slow, I discovered that not only are zero blocks are being cached in full, they also are hashed and take up MD5 cache slots. This delivers the a triple whammy when trying to zero large chunks of thinly-provisioned space (like, say, a whole 16TB virtual disk). Each block zeroed evicts other blocks from the block cache, requires writing to disk if using a file-backed cache, requires hashing (a serious throughput limiter when competing against /dev/zero), and blocks new block writes when the MD5 cache slots are inevitably exhausted until new ones are available. This all conspires to reduce the nigh-instantaneous "Discarding device blocks" step during a typical ext4 format to a hours-long procedure.

A more adequate solution would be to perhaps store an extents list in memory describing valid blocks in S3, and issue the actual deletes asynchronously. Neither data cache space nor an MD5 cache slot would not be needed for an empty block, since it would be easy to check against the valid extents list in memory.

**Comment by archiecobbs** [comment]
You are correct about this. A couple of points...

Filesystem initialization is a use case that matches poorly with how s3backer caching is optimized, namely, under the assumption that normal disk usage doesn't involve reading and writing a high percentage of blocks that are entirely zero. For ext4 filesystem initialization of course that assumption is false.

As a simple workaround, filesystem initialization can be performed with both caches disabled.

Regarding the MD5 cache, you have to cache zero blocks just like any other. Of course the MD5 cache only stores MD5 values, not actual block data.

Regarding the block cache, yes it is pretty dumb to be allocating memory for a block full of zeroes. This may be an easy improvement to make by adding a simple bit flag. However, for the on-disk case this is harder because it changes the disk format.

The MD5 cache and the block cache use ordinary cache entries for zero blocks, i.e., they don't have special structures for zero extents. This was done to keep things simple. For example, the on-disk format of the block cache would get more complicated if it had to store extents as well.

**Comment by archiecobbs** [comment]
One final comment: to avoid slow mkfs, it's important to do two things:
  1. Erase the filesystem before starting via `s3backer --erase`
  1. Make sure you include the `--listBlocks` flag

Closing issue for now. Re-open if there is any news.
