### ISSUE TITLE
Feature Request: GET Range support for smaller local blocks, big blocks on S3

### ISSUE THREAD

**Issue by neocogent** [archiecobbs/s3backer#72]
According to the docs S3 does support "Range" header GET requests. Have you looked into this before and found it workable? I didn't see any mention in the docs and it seems a very worthwhile cost optimization.

The advantage would be great for small byte length reads (which happens to be my use case). eg. a local block size of 512 bytes but 10 MB s3 blocks would minimize the cost of uploading large files (say 25 GB data file), but still allow reading small parts quickly and for low cost (low xfer cost). So the best of both worlds, compared to high cost of uploading small blocks (PUT req fee).

In my case I have a large 25 GB data file and which is read-only after creation, but it is read in small byte sizes. So many small reads cause either big blocks to be downloaded, or when created many PUT requests to store.

**Comment by archiecobbs** [comment]
This makes sense in theory but in practice would be difficult because the whole internal design of s3backer is based on a block-level granularity.

Are you using the block cache? That should help somewhat, depending on your read pattern.

Also, could you use a smaller block size? It's not stated anywhere but of course one factor in choosing a block size is the latency of reading a single block. If the block size is large relative to your network speed then you can have this issue.

**Comment by neocogent** [comment]
I'd like to use a smaller block size but the cost of initially putting them up is high. 25GB @ 256K = 100,000 blks ~$5 to store. Or more if I truly made it as low as I'd like, say 4K. Each read I do is typically around 1K.

I knew the internal design was block based. I haven't looked to see exactly how that manifests. To do something like I suggest you would have to be able to set two different block sizes - one on s3 and one locally. When doing PUT you'd store the outgoing size but when GET you'd request a consecutive multiple of the local block size and fill multiple blocks. That would be a pretty big change but depending how sizes are defined and used throughout the code it may be not that much change. Obviously the big block needs to be a exact multiple of the smaller one. 

I only suggest it as an idea because it could potentially offer very significant savings and speed increase for smaller size reads common in some use cases. The cost/MB access would drop greatly when, eg. only transferring 4k down instead of 1MB (cost effective block write size).

Regarding read pattern - unfortunately it's very random. The exact case is a "blob" companion file to a mysql db, as a web backend. So most user interaction is to the db and I keep that in local SSD storage (120GB intensive indexing). The side file is 65GB and referenced by the db. So when a user looks up some primary data, sometimes they need a bit from the blob file. I want to save space/cost by moving about 25GB of the 65GB blob files out to s3. The access to this blob is unpredictable as it depends on user lookup patterns; very non sequential. 

So my theory was optimally you would store 2500 x 10 MB blocks to s3. But request in more granular size blocks of 4K. Cost for initial writes is ~12 cents. Cost for random reads is also low, about 14k req/cent. Ideal for random I/O. It reminds me of SSD IOPS where you gain faster responsiveness to small I/O.

**Comment by archiecobbs** [comment]
OK I took a look again at the code and actually it looks like it might be fairly straightforward to implement (though not by me because I'm too busy right now).

The API in `s3backer.h` already defines a `read_block_part()` method which asks to read a part of a block. Currently all implementations delegate to `block_part_read_block_part()` (in `block_part.c`) which is just a "dumb" implementation that reads the whole block, then returns the portion requested.

You would have to provide new implementations of this method in `http_io.c`, `ec_protect.c`, and `block_cache.c` (if you want to use the block cache).

One simple design that doesn't try to cache partial reads would be:

1. Add a new configuration parameter `--range-read` which would define a ratio such that a partial block read of that fraction or less would result in a direct, uncached read from S3. For example,  `--range-read=0.15` would set a ratio of 15%.
1. Update `ec_protect.c`, and `block_cache.c` to implement `read_block_part()` such that if the block is not already cached, and the read size is less than the `--range-read` percentage of a whole block, the read would simply pass through to the next layer, and the result would not be cached (in the case of `ec_protect.c`, it would still have to impose its eventual consistency delay if necessary).
1. Update `http_io.c` to implement `read_block_part()` such that it would perform a range read instead of reading the whole block.

**Comment by archiecobbs** [comment]
Not planning to implement this for now.
