### ISSUE TITLE
Missing zlib1g-dev to be installed for compiling

### ISSUE THREAD

**Issue by windware** [archiecobbs/s3backer#98]
Wiki page says,

> $ sudo apt-get install libcurl4-openssl-dev libfuse-dev libexpat1-dev libssl-dev

but it also needs zlib1g-dev for './configure' to run.
Tested on Ubuntu 18.04.

And for those who don't have build tools, these are also required.

> $ sudo apt-get install autoconf build-essential

**Comment by archiecobbs** [comment]
Thanks, wiki updated to include `zlib1g-dev` for Ubuntu.

**Comment by windware** [comment]
Also had to install 'pkg-config' on another Ubuntu 18.04.
I think you want to update the wiki to add 

> $ sudo apt-get install autoconf build-essential pkg-config

And also, 'autogen.sh' seems to be missing from the latest 1.5.0 download and it built fine without running it.

**Comment by archiecobbs** [comment]
`autogen.sh` is only used when building from source control.  That's different from building from distribution package.

Please ignore the "Releases" that Github automatically creates without my knowledge or ability to stop them.

Instead, download from the [Downloads](https://github.com/archiecobbs/s3backer/wiki/Downloads) wiki page.

The real distribution package doesn't have `autogen.sh` because it doesn't need it. Just run `./configure`.

**Comment by archiecobbs** [comment]
I see now that the "Build & Install" wiki page had a bug. It should not have included the `autogen.sh` step in the "Building And Installing From Distribution Source" instructions.

Sorry for the confusion.

**Comment by windware** [comment]
You might also want to add 'build-essential' and 'autoconf' packages as requirements for people who aren't familiar with the process.
